hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      colorlog:
        (): colorlog.ColoredFormatter
        format: '[%(cyan)s%(asctime)s%(reset)s][%(purple)sHYDRA%(reset)s] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: colorlog
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
      colorlog:
        (): colorlog.ColoredFormatter
        format: '[%(cyan)s%(asctime)s%(reset)s][%(blue)s%(name)s%(reset)s][%(log_color)s%(levelname)s%(reset)s]
          - %(message)s'
        log_colors:
          DEBUG: purple
          INFO: green
          WARNING: yellow
          ERROR: red
          CRITICAL: red
    handlers:
      console:
        class: logging.StreamHandler
        formatter: colorlog
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - seed=2,3
  job:
    name: main
    chdir: null
    override_dirname: seed=2,3
    id: ???
    num: ???
    config_name: corners_llm_TROI_po_planning_agent.yaml
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: /pfs/data6/home/tu/tu_tu/tu_zxoau23/pomdp_coder
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: hydra_plugins.hydra_colorlog.conf
      schema: pkg
      provider: hydra-colorlog
    - path: /pfs/data6/home/tu/tu_tu/tu_zxoau23/pomdp_coder/uncertain_worms/config/approaches/ours
      schema: file
      provider: command-line
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: colorlog
      hydra/hydra_logging: colorlog
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
max_steps: 30
num_episodes: 10
seed: 0
gamma: 0.98
save_log: false
replay_path: None
actions:
- 0
- 1
- 2
- 3
- 4
- 5
env_name: CornerGoalRandom-Empty-10x10-v0
env:
  _target_: uncertain_worms.environments.minigrid.minigrid_env.MinigridEnvironment
  fully_obs: false
  env_name: ${env_name}
agent:
  _target_: uncertain_worms.policies.partially_obs_planning_agent.LLMPartiallyObsPlanningAgent
  max_attempts: 250000
  num_particles: 100
  num_model_attempts: 5
  fully_obs: false
  env_code_path: environments/minigrid
  actions:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  learn_transition: true
  learn_initial: true
  learn_reward: true
  learn_observation: true
  use_online: true
  use_offline: true
  dataset_path: environments/minigrid/trajectory_data/${env_name}.pkl
  env_description: ''
  empty_state:
    _target_: uncertain_worms.environments.minigrid.minigrid_env.minigrid_empty_state_gen
    env_name: ${env_name}
  empty_observation:
    _target_: uncertain_worms.environments.minigrid.minigrid_env.minigrid_empty_observation_gen
  planner:
    _target_: uncertain_worms.planners.PO_DAStar.PO_DAStar
    actions:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    empty_observation:
      _target_: uncertain_worms.environments.minigrid.minigrid_env.minigrid_empty_observation_gen
    initial_model:
      _target_: uncertain_worms.structs.empty_initial_model_gen
    transition_model:
      _target_: uncertain_worms.structs.empty_transition_model_gen
    reward_model:
      _target_: uncertain_worms.structs.empty_reward_model_gen
    observation_model:
      _target_: uncertain_worms.structs.empty_observation_model_gen
